insert into arm_shd_database.shch (name, code, deleted) values ('Львівська дистанція сигналізації та зв\'язку', 'ШЧ-1', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Львівська дистанція зв\'язку', 'ШЧ-2', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Здолбунівська дистанція сигналізації та зв\'язку', 'ШЧ-3', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Стрийська дистанція сигналізації та зв\'язку', 'ШЧ-4', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Івано-Франківська дистанція сигналізації та зв\'язку', 'ШЧ-5', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Сарненська дистанція сигналізації та зв\'язку', 'ШЧ-6', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Тернопільська дистанція сигналізації та зв\'язку', 'ШЧ-8', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Мукачівська дистанція сигналізації та зв\'язку', 'ШЧ-9', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Ужгородська дистанція сигналізації та зв\'язку', 'ШЧ-10', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Чернівецька дистанція сигналізації та зв\'язку', 'ШЧ-11', 0);
insert into arm_shd_database.shch (name, code, deleted) values ('Ковельська дистанція сигналізації та зв\'язку', 'ШЧ-12', 0);
