INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Program Developer', 'Author');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Адміністратор', 'Адмін');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Старший диспетчер служби сигналізації та зв\'язку', 'ШДС');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер служби сигналізації та зв\'язку', 'ШД');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-1', 'ШЧД-1');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-2', 'ШЧД-2');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-3', 'ШЧД-3');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-4', 'ШЧД-4');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-5', 'ШЧД-5');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-6', 'ШЧД-6');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-8', 'ШЧД-8');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-9', 'ШЧД-9');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-10', 'ШЧД-10');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-11', 'ШЧД-11');
INSERT INTO arm_shd_database.positions (position_full, position_short) VALUES ('Диспетчер дистанції сигналізації та зв\'язку ШЧ-12', 'ШЧД-12');